name: fracture-physprops-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pip:
    - geoana==0.0.5
    - pymatsolver==0.1.2
    - discretize==0.3.8
    - SimPEG==0.10.4
    - git+https://github.com/simpeg-research/casingSimulations.git@0.0.7
