name: fracture-physprops-environment

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - numpy
  - scipy
  - matplotlib
  - ipywidgets>=0.6.0
  - mkl
  - pip:
    - pymatsolver
    - discretize
    - SimPEG
